### PR TITLE
fix: #34 Parser not works anymore if useReadMe is disabled

### LINKED ISSUE #34: Parser not works anymore if useReadMe is disabled
Parser not works because it use wrong basedir for api lookup
```ts
  const apiDocsPath = options.baseDirectory || path.resolve('./', 'docs', 'api');
  const structuresPath = path.resolve(apiDocsPath, 'structures');
```
Leads to wrong api base Path.

```
{ [Error: ENOENT: no such file or directory, scandir 'electron-master/structures']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path:
   'electron-master/structures' }
```

commit: https://github.com/electron/docs-parser/commit/d8bec24c5f4ad27bc440ab6c56a4a7ab9d4c4d32
https://github.com/electron/docs-parser/blob/d8bec24c5f4ad27bc440ab6c56a4a7ab9d4c4d32/src/index.ts#L15

### PR DESCRIPTION
**Pull request by MCMicS**

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ type ParseOptions = {
 export async function parseDocs(options: ParseOptions) {
   const packageMode = options.packageMode || 'single';
 
-  const apiDocsPath = options.baseDirectory || path.resolve('./', 'docs', 'api');
+  const apiDocsPath = path.resolve('./', 'docs', 'api');
```
Comment (MarshallOfSound) [inline src/index.ts:15]:
```suggestion
  const apiDocsPath = path.resolve(options.baseDirectory, 'docs', 'api');
```

To restore original behavior
